# eslint configuration
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true
env:
  browser: true
  es6: true
  jasmine: true
  node: true
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  arrow-parens:
    - error
    - always

